name: Build to GHCR and Deploy Locally

on:
  push:
    branches: [ "main" ]

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          no-cache: true
          tags: ghcr.io/mustafa12ah/project2/backend:latest  # Forced to strictly lowercase

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout configuration files
        uses: actions/checkout@v4

      - name: Log in to GHCR on PC
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and Run App
        run: |
          cd ~/Desktop/project2/Expense_Tracker
          docker compose pull backend
          docker compose up -d backend
